### ISSUE TITLE
JS reserved words can cause errors in amber-visit

### ISSUE THREAD

**Issue by kazoompa** [obiba/amber-studio#12]
- Create an interview
- Name the step `map` (JS reserved word)
- Start the interview in `amber-visit`

When you try to save the interview the app crashes since it cannot find the `map` function:

```
itw.js:283 Uncaught (in promise) TypeError: itw.value.steps.map is not a function
    at saveRecord (itw.js:283:12)
    at Proxy.completeRecord (itw.js:259:14)
    at Proxy.<anonymous> (pinia.mjs:1375:30)
    at store.<computed> (pinia.mjs:930:50)
    at Proxy.onComplete (InterviewStep.vue:489:23)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at emit (runtime-core.esm-bundler.js:664:5)
    at navigateOnClick (quasar.esm.js:2968:7)
    at onClick (quasar.esm.js:3700:7)
```

Rename that and everything works

**Comment by kazoompa** [comment]
Will try a few other reserved words...

**Comment by ymarcon** [comment]
Is it fixed?
